# Database Configuration
spring.datasource.dbdept.jdbc-url=jdbc:mysql://localhost:3306/department
spring.datasource.dbdept.username=root
spring.datasource.dbdept.password=1234
spring.datasource.dbdept.driver-class-name=com.mysql.cj.jdbc.Driver

# Database Configuration
spring.datasource.empdb.jdbc-url=jdbc:mysql://localhost:3306/employee
spring.datasource.empdb.username=root
spring.datasource.empdb.password=1234
spring.datasource.empdb.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Expose actuator endpoints
management.endpoints.web.exposure.include=*
# Enable info endpoint to show custom properties
management.info.env.enabled=true

# Application information
info.app.name=Employee Department Service
info.app.version=1.0.0
info.app.description=Spring Boot Actuator Demo
